version: '2'
services:
  web6:
    image: nginx
    environment:
    - SERVICE_80_NAME=great6
    - SERVICE_80_ID=great6
    restart: always
    mem_limit: 128m
    network_mode: bridge
    expose:
      - "80"
    ports:
      - "80"

